### PR TITLE
fix(database/pg): fix duplicate index

### LINKED ISSUE #982: pg create table failed: index `idx` already exist

### PR DESCRIPTION
**Pull request by lianxmfor**
resolve #982

### CODE REVIEW

File: internal/database/dbutil/schema.go [hunk 1]
```diff
@@ -68,10 +68,12 @@ func BuildIndexDDL(tableName string, indexName string, fields []string, backend
 	qt := QuoteFn(backend)
 	switch backend {
 	case types.BackendCassandra,
-		types.BackendPostgres,
 		types.BackendMySQL,
 		types.BackendSQLite:
 		return fmt.Sprintf("CREATE INDEX %s ON %s (%s)", qt(indexName), qt(tableName), qt(fields...))
+	case types.BackendPostgres:
+		// see: https://stackoverflow.com/a/27307016/16428442
```
Comment (YikSanChan) [inline internal/database/dbutil/schema.go:75]:
```
// omit the name when creating the index, and PG will assign a unique name automatically.
// see: https://stackoverflow.com/a/27307016/16428442
```

**Review by YikSanChan — APPROVED** [review]
Curious how do you uncover this problem 🤔

File: internal/database/dbutil/schema.go (hunk 1 above)
Comment (lianxmfor) [reply internal/database/dbutil/schema.go:76]: done
