### PR TITLE
fix(online/import): fix importOpt.ExportError check

### LINKED ISSUE #1146: bug: after sync stream features, the value of oomcli get online is empty
To reproduce:

```shell
$ oomcli init
$ oomcli apply -f /tmp/tmp/meta.yaml
applied
$ oomcli get meta entity -o yaml
items:
  - kind: Entity
    name: user
    description: user
    groups:
      - name: user-click
        category: stream
        snapshot-interval: 1s
        description: user click post feature
        features:
          - name: last_5_click_posts
            value-type: string
            description: user last 5 click posts
          - name: number_of_user_starred_posts
            value-type: int64
            description: number of posts that users starred today
  - kind: Entity
    name: device
    description: device
    groups:
      - name: phone
        category: batch
        description: phone
        features:
          - name: price
            value-type: int64
            description: price
          - name: model
            value-type: string
            description: model
$ cat user_click.csv
user,unix_milli,last_5_click_posts,number_of_user_starred_posts
1,1644285708319,"1,2",10
2,1644285708319,"2,3",10
$ oomcli import --group user-click --input-file user_click.csv --description 'test data'
importing features ...
succeeded
RevisionID: 0
$ oomcli sync --group-name user-click
syncing features ...
INSERT INTO "tmp_online_stream_1644312413532942845" ("user","last_5_click_posts","number_of_user_starred_posts") VALUES (?, ?, ?),(?, ?, ?)
1
1,2
10
2
2,3
10
succeeded.
$ oomcli get online -k 1 --feature user-click.last_5_click_posts
+------+-------------------------------+
| user | user-click.last_5_click_posts |
+------+-------------------------------+
|    1 |                               |
+------+-------------------------------+
$ litecli /tmp/tmp/oomstore.db
Version: 1.7.0
Mail: https://groups.google.com/forum/#!forum/litecli-users
GitHub: https://github.com/dbcli/litecli
/tmp/tmp/oomstore.db> .tables ;
+-----------------------------------------+
| name                                    |
+-----------------------------------------+
| entity                                  |
| feature                                 |
| feature_group                           |
| feature_group_revision                  |
| offline_stream_cdc_1_0                  |
| offline_stream_cdc_1_1644285708319      |
| offline_stream_snapshot_1_0             |
| offline_stream_snapshot_1_1644285708319 |
| online_stream_1                         |
| tmp_export_entity_1644312413504106444   |
| tmp_online_stream_1644312413532942845   |
+-----------------------------------------+
Time: 0.007s
/tmp/tmp/oomstore.db> select * from online_stream_1 ;
0 rows in set
Time: 0.000s
/tmp/tmp/oomstore.db> select * from tmp_online_stream_1644312413532942845 ;
+------+--------------------+------------------------------+
| user | last_5_click_posts | number_of_user_starred_posts |
+------+--------------------+------------------------------+
| 1    | 1,2                | 10                           |
| 2    | 2,3                | 10                           |
+------+--------------------+------------------------------+
2 rows in set
Time: 0.004s
/tmp/tmp/oomstore.db>
```

### PR DESCRIPTION
**Pull request by lianxmfor**
fix #1146

### CODE REVIEW

File: internal/database/online/sqlutil/import.go [hunk 1]
```diff
@@ -49,8 +50,15 @@ func Import(ctx context.Context, db *sqlx.DB, opt online.ImportOpt, backend type
 			return err
 		}
 		if opt.ExportError != nil {
-			return <-opt.ExportError
+			select {
+			case err := <-opt.ExportError:
+				if err != nil {
```
Comment (lianxmfor) [inline internal/database/online/sqlutil/import.go:55]: if `opt.ExportError` closed. the case will run, there is a demo:

https://go.dev/play/p/Se1Tw08Kr2J

**Review by jinghancc — APPROVED** [review]
LGTM

**Review by wfxr — APPROVED** [review]
LGTM
